# To allow the SCC privileged to be used by the Shipwright Pods (OKD/Openshift-specific)
# This is needed for the buildah strategy to work until we have a non-privileged alternative
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-privileged
subjects:
  - kind: ServiceAccount
    name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
