apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: release
  namespace: okd
spec:
  lookupPolicy:
    local: true
  tags:
    - name: builder
    - name: base
    - name: machine-config-operator
    - name: cluster-version-operator
