apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: base
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/images'
      ref: release-4.12
    contextDir: base
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:builder"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:base'
