apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: csi-node-driver-registrar
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/csi-node-driver-registrar'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.12'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openshift
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:csi-node-driver-registrar'
