apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: machine-os-images
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/machine-os-images'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:installer'
        as:
          - 'registry.ci.openshift.org/ocp/4.11:installer'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      buildArgs:
      - name: DIRECT_DOWNLOAD
        value: "true"
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:machine-os-images'
