apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kuryr-cni
  namespace: okd
  failureDescription: kuryr-cni-rpm-base fails to build
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/kuryr-kubernetes'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.11'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: openshift-kuryr-cni-rhel8.Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:kuryr-cni-rpm-base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:kuryr-cni'
