apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: agent-installer-csr-approver
  namespace: okd
  failureDescription: |
    needs cli
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/assisted-installer'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11'
      - from:
          kind: ImageStreamTag
          name: 'release:cli'
        as:
          - 'registry.ci.openshift.org/ocp/4.11:cli'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.assisted-installer-controller.ocp
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:agent-installer-csr-approver'
