apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cloud-credential-operator
  namespace: okd
  failureDescription: |
    [1/2] STEP 5/6: RUN go build -ldflags "-X $GO_PACKAGE/pkg/version.versionFromGit=$(git describe --long --tags --abbrev=7 --match 'v[0-9]*')" ./cmd/cloud-credential-operator
    fatal: No names found, cannot describe anything
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cloud-credential-operator'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.12'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cloud-credential-operator'
