apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: batched-build
  namespace: okd
spec:
  params:
    - name: initial-image
      type: string
      description: Initial image to import
      default: quay.io/vrutkovs/okd-release:4.12.0-0.okd-centos9-full-rebuild
    - name: result-mirror-location
      type: string
      description: Location to mirror resulting images
      default: quay.io/vrutkovs/okd-release
    - name: result-image
      type: string
      description: Resulting release location
      default: quay.io/vrutkovs/okd-release:4.12.0-0.okd-centos9-rebuild
    - name: result-image-name
      type: string
      description: Internal release name
      default: 4.12.0-0.okd-centos9-rebuild
  workspaces:
    - name: push-credentials
  tasks:
    - name: new-release
      taskRef:
        name: openshift-client
        kind: ClusterTask
      timeout: "2h0m0s"
      workspaces:
      - name: manifest-dir
        workspace: push-credentials
      params:
        - name: SCRIPT
          value: |
            oc adm release new \
            --registry-config=$(workspaces.manifest-dir.path)/auth.json \
            --from-image-stream release \
            --insecure=true \
            --mirror $(params.result-mirror-location) \
            --to-image $(params.result-image) \
            --name=$(params.result-image-name)
