apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: partial-build
  namespace: okd
spec:
  params:
    - name: initial-image
      type: string
      description: Initial image to import
      default: registry.ci.openshift.org/origin/release:4.12.0-0.okd-2022-07-25-043310
    - name: result-mirror-location
      type: string
      description: Location to mirror resulting images
      default: quay.io/vrutkovs/okd-release
    - name: result-image
      type: string
      description: Resulting release location
      default: quay.io/vrutkovs/okd-release:4.12.0-0.okd-centos9-rebuild
    - name: result-image-name
      type: string
      description: Internal release name
      default: 4.12.0-0.okd-centos9-rebuild
  workspaces:
    - name: push-credentials
  tasks:
    - name: initial-import
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc adm release mirror \
              --from $(params.initial-image) \
              --to-image-stream release
    - name: prepare-build-images
      runAfter:
      - initial-import
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build builder --wait && \
            oc start-build forked-dockerfiles --wait && \
            oc start-build base --wait
    - name: build-01-01
      runAfter:
      - prepare-build-images
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build agent-installer-node-agent --wait
    - name: build-01-02
      runAfter:
      - prepare-build-images
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build agent-installer-orchestrator --wait
    - name: build-01-03
      runAfter:
      - prepare-build-images
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build alibaba-cloud-controller-manager --wait
    - name: build-01-04
      runAfter:
      - prepare-build-images
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build alibaba-cloud-csi-driver --wait
    - name: build-01-05
      runAfter:
      - prepare-build-images
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build alibaba-disk-csi-driver-operator --wait
    - name: build-02-01
      runAfter:
      - build-01-01
      - build-01-02
      - build-01-03
      - build-01-04
      - build-01-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build alibaba-machine-controllers --wait
    - name: build-02-02
      runAfter:
      - build-01-01
      - build-01-02
      - build-01-03
      - build-01-04
      - build-01-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build apiserver-network-proxy --wait
    - name: build-02-03
      runAfter:
      - build-01-01
      - build-01-02
      - build-01-03
      - build-01-04
      - build-01-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build aws-cloud-controller-manager --wait
    - name: build-02-04
      runAfter:
      - build-01-01
      - build-01-02
      - build-01-03
      - build-01-04
      - build-01-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build aws-cluster-api-controllers --wait
    - name: build-02-05
      runAfter:
      - build-01-01
      - build-01-02
      - build-01-03
      - build-01-04
      - build-01-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build aws-ebs-csi-driver-operator --wait
    - name: build-03-01
      runAfter:
      - build-02-01
      - build-02-02
      - build-02-03
      - build-02-04
      - build-02-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build machine-api-operator --wait
    - name: build-03-02
      runAfter:
      - build-02-01
      - build-02-02
      - build-02-03
      - build-02-04
      - build-02-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build machine-config-operator --wait
    - name: build-03-03
      runAfter:
      - build-02-01
      - build-02-02
      - build-02-03
      - build-02-04
      - build-02-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build coredns --wait
    - name: build-03-04
      runAfter:
      - build-02-01
      - build-02-02
      - build-02-03
      - build-02-04
      - build-02-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build etcd --wait
    - name: build-03-05
      runAfter:
      - build-02-01
      - build-02-02
      - build-02-03
      - build-02-04
      - build-02-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build openshift-apiserver --wait
    - name: new-release
      runAfter:
      - build-02-01
      - build-02-02
      - build-02-03
      - build-02-04
      - build-02-05
      taskRef:
        name: openshift-client
        kind: ClusterTask
      timeout: "2h0m0s"
      workspaces:
      - name: manifest-dir
        workspace: push-credentials
      params:
        - name: SCRIPT
          value: |
            oc adm release new \
            --registry-config=$(workspaces.manifest-dir.path)/auth.json \
            --from-image-stream release \
            --insecure=true \
            --mirror $(params.result-mirror-location) \
            --to-image $(params.result-image) \
            --name=$(params.result-image-name) \
            --include=baremetal-runtimecfg,keepalived-ipfailover,pod,baremetal-machine-controllers,gcp-machine-controllers,ibmcloud-machine-controllers,libvirt-machine-controllers,nutanix-machine-controllers,openstack-machine-api-provider,openstack-machine-controllers,ovirt-machine-controllers,powervs-machine-controllers,alibaba-machine-controllers
