apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: release
  namespace: okd
spec:
  lookupPolicy:
    local: true
  tags:
    - name: rhel-coreos
      from:
        kind: DockerImage
        name: quay.io/coreos-assembler/fcos:stable
      referencePolicy:
        type: Source
