apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: forked-dockerfiles
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/okd-project/okd-centos9-rebuild'
      ref: main
    contextDir: forks
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'release:forked-dockerfiles'
