apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: builder
  labels:
    builder-replacement: skip
    skip-release-branch: "true"
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/okd-project/images'
      ref: main
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: okd-builder.Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "tools:centos9"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:builder'
