apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: branding
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/origin-branding'
      ref: master
    contextDir: .
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'release:branding'
