apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: baremetal-installer
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/installer'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.11'
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/baremetal-installer/Dockerfile.centos9
          destinationDir: "./images/baremetal"
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/baremetal/Dockerfile.centos9
      buildArgs:
          - name: "TAGS"
            value: "baremetal libvirt okd"
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:baremetal-installer'
