apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: deployer
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/oc'
      ref: release-4.12
    contextDir: images/deployer
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:deployer'
