apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: etcd
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/etcd'
      ref: openshift-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-etcd-golang-1.16'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:etcd'
