apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ironic-agent
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ironic-agent-image'
      ref: release-4.12
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.okd
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:ironic-agent'
