apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: installer-artifacts
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/installer'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/installer-artifacts/Dockerfile.rhel
      buildArgs:
          - name: "TAGS"
            value: "okd"
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:installer-artifacts'
