apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: installer-artifacts
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/installer'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.11'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: images/installer-artifacts/Dockerfile.rhel
      buildArgs:
          - name: "TAGS"
            value: "okd"
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:installer-artifacts'
