apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ibmcloud-machine-controllers
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cluster-api-provider-ibmcloud'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:ibmcloud-machine-controllers'
