apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: operator-registry
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/operator-framework-olm'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.12'
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/operator-registry/Dockerfile.centos9
          destinationDir: "."
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:operator-registry'
