apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: operator-marketplace
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/operator-framework/operator-marketplace'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/openshift/release:golang-1.17'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.okd
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:operator-marketplace'
