apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: service-ca-operator
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/service-ca-operator'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.17-openshift-4.10'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel7
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:service-ca-operator'
