apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sdn
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/sdn'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/sdn/Dockerfile.centos9
          destinationDir: "./images/sdn"
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/sdn/Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:sdn'
