apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cli-artifacts
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/oc'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11'
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/cli-artifacts/Dockerfile.centos9
          destinationDir: "./images/cli-artifacts"
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/cli-artifacts/Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:cli"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cli-artifacts'
