apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: network-tools
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/network-tools'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.12'
      - from:
          kind: ImageStreamTag
          name: 'release:ovn-kubernetes'
        as:
          - 'registry.ci.openshift.org/ocp/4.12:ovn-kubernetes'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:tools"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:network-tools'
