apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hyperkube
  namespace: okd
  failureDescription: |
    [1/2] STEP 4/4: RUN make WHAT='cmd/kube-apiserver cmd/kube-controller-manager cmd/kube-scheduler cmd/kubelet cmd/watch-termination' && mkdir -p /tmp/build && cp openshift-hack/images/hyperkube/hyperkube /tmp/build && cp /go/src/k8s.io/kubernetes/_output/local/bin/linux/$(go env GOARCH)/{kube-apiserver,kube-controller-manager,kube-scheduler,kubelet,watch-termination} /tmp/build
    +++ [0716 07:13:47] Building go targets for linux/amd64
    k8s.io/kubernetes/hack/make-rules/helpers/go2make (non-static)
    find: 'rsync': No such file or directory
    +++ [0716 07:14:06] Building go targets for linux/amd64
    k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen (non-static)
    find: 'rsync': No such file or directory
    find: 'rsync': No such file or directory
    +++ [0716 07:14:13] Generating prerelease lifecycle code for 26 targets
    ./hack/run-in-gopath.sh: line 34: _output/bin/prerelease-lifecycle-gen: Permission denied
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/kubernetes'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: openshift-hack/images/hyperkube/Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:hyperkube'
