apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: haproxy-router
  namespace: okd
  failureDescription: |
    STEP 2/11: RUN INSTALL_PKGS="haproxy22 rsyslog procps-ng util-linux" && yum install -y $INSTALL_PKGS && rpm -V $INSTALL_PKGS && yum clean all && mkdir -p /var/lib/haproxy/router/{certs,cacerts,whitelists} && mkdir -p /var/lib/haproxy/{conf/.tmp,run,bin,log} && touch /var/lib/haproxy/conf/{{os_http_be,os_edge_reencrypt_be,os_tcp_be,os_sni_passthrough,os_route_http_redirect,cert_config,os_wildcard_domain}.map,haproxy.config} && setcap 'cap_net_bind_service=ep' /usr/sbin/haproxy && chown -R :0 /var/lib/haproxy && chmod -R g+w /var/lib/haproxy && sed -i 's/SECLEVEL=2/SECLEVEL=1/g' /etc/crypto-policies/back-ends/opensslcnf.config
    CentOS Stream 9 - BaseOS 4.6 MB/s | 5.7 MB 00:01
    CentOS Stream 9 - AppStream 13 MB/s | 14 MB 00:01
    CentOS Stream 9 - Extras packages 7.9 kB/s | 8.5 kB 00:01
    Last metadata expiration check: 0:00:01 ago on Sat Jul 16 07:18:00 2022.
    No match for argument: haproxy22
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/router'
      ref: release-4.12
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/router/haproxy/Dockerfile.rhel8
      from:
        kind: "ImageStreamTag"
        name: "release:haproxy-router-base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:haproxy-router'
