apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cluster-node-tuning-operator
  namespace: okd
  failureDescription: |
    [3/3] STEP 12/16: RUN INSTALL_PKGS=" tuned tuned-profiles-atomic tuned-profiles-cpu-partitioning tuned-profiles-mssql tuned-profiles-nfv tuned-profiles-nfv-guest tuned-profiles-nfv-host tuned-profiles-openshift tuned-profiles-oracle tuned-profiles-postgresql tuned-profiles-realtime tuned-profiles-sap tuned-profiles-sap-hana tuned-profiles-spectrumscale nmap-ncat procps-ng" && mkdir -p /etc/grub.d/ /boot && dnf install --setopt=tsflags=nodocs -y $INSTALL_PKGS && rpm -V $INSTALL_PKGS && cp -a /var/lib/tuned/tuned/stalld/{stalld,scripts/throttlectl.sh} /usr/local/bin && rm -rf /var/lib/tuned/tuned && touch /etc/sysctl.conf $APP_ROOT/provider && dnf clean all && rm -rf /var/cache/yum ~/patches /root/rpms && useradd -r -u 499 cluster-node-tuning-operator
    CentOS Stream 9 - BaseOS 5.2 MB/s | 5.7 MB 00:01
    CentOS Stream 9 - AppStream 21 MB/s | 14 MB 00:00
    CentOS Stream 9 - Extras packages 19 kB/s | 8.5 kB 00:00
    No match for argument: tuned-profiles-nfv
    No match for argument: tuned-profiles-nfv-guest
    No match for argument: tuned-profiles-nfv-host
    No match for argument: tuned-profiles-openshift
    No match for argument: tuned-profiles-realtime
    No match for argument: tuned-profiles-sap
    No match for argument: tuned-profiles-sap-hana
    Package procps-ng-3.3.17-5.el9.x86_64 is already installed.
    Error: Unable to find a match: tuned-profiles-nfv tuned-profiles-nfv-guest tuned-profiles-nfv-host tuned-profiles-openshift tuned-profiles-realtime tuned-profiles-sap tuned-profiles-sap-hana
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cluster-node-tuning-operator'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.12'
      - from:
          kind: ImageStreamTag
          name: 'release:base'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-base-openshift-4.12'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel8
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cluster-node-tuning-operator'
